In [1]:
# import numpy library
import numpy as np

In [2]:
# Create a 3x3 identity matrix and multiply by 9 to make diagonal = 9
matrix = np.eye(3) * 9

# Print result
print(matrix)

[[9. 0. 0.]
 [0. 9. 0.]
 [0. 0. 9.]]


In [3]:
# Create 7x7 matrix of ones
matrix = np.ones((7,7))

print(matrix)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [4]:
# Create a 5x5 hole of zeros inside the matrix
matrix[1:6, 1:6] = 0

print(matrix)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [5]:
# Place number 5 in the center of the matrix
matrix[3,3] = 5

print(matrix)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 5. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
# Ask user for n
n = int(input("Enter n: "))

Enter n: 7


In [7]:
# Create array using broadcasting
arr = np.arange(1, n+1)
arr = np.tile(arr, (n,1))

print(arr)

[[1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]
 [1 2 3 4 5 6 7]]


In [8]:
# Generate random 5x5 matrix from 0 to 100
matrix = np.random.randint(0, 101, (5,5))

print(matrix)

[[29 31 34 74 15]
 [41 59 87 65 25]
 [33 97 88 12 68]
 [ 4 77 20 59 29]
 [35 28 71 72 16]]


In [9]:
# Find maximum value in each row
print(matrix.max(axis=1))

[74 87 97 77 72]


In [10]:
# Find sum of each column
print(matrix.sum(axis=0))

[142 292 300 282 153]


In [11]:
# Calculate overall mean
print(matrix.mean())

46.76


In [12]:
# Boolean masking: values > 50 become 1, others 0
new_matrix = (matrix > 50).astype(int)

print(new_matrix)

[[0 0 0 1 0]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [0 1 0 1 0]
 [0 0 1 1 0]]


In [13]:
# Create array from 1 to 30 and reshape to 6x5
arr = np.arange(1,31).reshape(6,5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [14]:
# Extract 2x2 square [[11,12],[16,17]]
print(arr[2:4, 0:2])

[[11 12]
 [16 17]]


In [15]:
# Extract elements [2, 8, 14, 20]
print(arr[[0,1,2,3], [1,2,3,4]])

[ 2  8 14 20]


In [16]:
# Get rows with even indices (0,2,4)
print(arr[::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [17]:
# Create scores array
scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])

print(scores)

[45 88 92 30 50 76 99 12 65]


In [18]:
# Print passing grades (>= 50)
print(scores[scores >= 50])

[88 92 50 76 99 65]


In [19]:
# Check if any student got 100
print(np.any(scores == 100))

False


In [20]:
# Check if all students passed
print(np.all(scores >= 50))

False
